accounts/urls.py
from django.urls import path, reverse_lazy
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path("register/", views.RegisterView.as_view(template_name="accounts/register.html"), name="register"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("edit-profile/", views.EditProfileView.as_view(), name="edit_profile"),
    path('change-password',
         auth_views.PasswordChangeView.as_view(template_name="accounts/change_password.html", success_url=reverse_lazy('accounts:change_password_done')), name='change_password'),
    path('change-password/done', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/change_password_done.html'), name='change_password_done'),
]

movie_rental/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', view=views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

account/views.py
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


class RegisterView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('account:login')
    template_name = "account/register.html"


class EditProfileView(UpdateView):
    fields = ['first_name', 'last_name']
    template_name = 'account/edit_profile.html'
    success_url = reverse_lazy('index')

    def get_object(self):
        return self.request.user

accounts/views.py
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


class RegisterView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('accounts:login')
    template_name = "accounts/register.html"


class EditProfileView(UpdateView):
    fields = ['first_name', 'last_name']
    template_name = 'accounts/edit_profile.html'
    success_url = reverse_lazy('index')

    def get_object(self):
        return self.request.user

movie_rental/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = "index.html"

accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body_block %}
<div class="row justify-content-center">
    <div class="col-6">
        <h1>Zmiana hasłeka</h1>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input class="btn btn-dark" type="submit" value="Zmień">
        </form>
    </div>
</div>
{% endblock body_block %}

accounts/templates/accounts/change_password_done.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body_block %}
<div class="row justify-content-center">
    <div class="col-12">
        <h1>Hasełko zmienione pomyślnie ;))</h1>
        <h6>Twoje hasełko zostało zmienione ;D</h6>
    </div>
</div>
{% endblock body_block %}

accounts/templates/accounts/edit_profile.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body_block %}
<div class="row justify-content-center">
    <div class="col-6">
        <h1>Edytowanko</h1>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="row">
                <div class="col">
                    <input class="btn btn-dark col-auto" type="submit" value="Edytuj :D">
                    <a class="btn btn-dark col-auto" href="{% url 'accounts:change_password' %}">Zmiana hasełka</a>
                </div>
            </div>
        </form>

    </div>
</div>
{% endblock body_block %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body_block %}
<div class="row justify-content-center">
    <div class="col-6">
        <h1>Logowanko</h1>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Login" class="btn btn-dark">
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body_block %}
<div class="row justify-content-center">
    <div class="col-6">
        <h1>Rejestracyjka</h1>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Register" class="btn btn-dark">
        </form>
    </div>
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>movie_rental</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-dark">
        <a class="navbar-brand" href="/">movie_rental</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Dostępne filmy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Moje filmy</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                	{% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:edit_profile' %}">Profil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:logout' %}">Wylogowanko</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:register' %}">Rejestrowanko</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Logowanko</a>
                        </li>
                    {% endif %}
                </ul>                
            </div>
    </nav>
    <div class="container">
    {% block body_block %}  
    {% endblock body_block %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}


{% block body_block %}
<div class="row justify-content-center p-5">
    <img src="{% static "/django.jpg" %}" alt="Django">
    <h1>Witam zaciekle na stronie głównej</h1>  
</div>
{% endblock body_block %}